### ISSUE TITLE
1 Last Request for 1.6.4, before you move on to your own mods

### ISSUE THREAD

**Issue by godemperoroftheworld** [wildex999/ICBM#6]
Hey man, Ive just found your work and it is AWESOME. Now, I have one big problem that if you fixed, it would make me the happiest person in the world. See, currently you can only add people to sentry turrets in creative, if you could make it so you can add people in survival it would totally make my day!

PLEASE consider doing this! Itll mean so much to me!

If you need any financial support I would be willing to donate 10-20 CAD!

**Comment by wildex999** [comment]
No need for financial support =)

I will try to take another look at this, however the problem is that the turrets and permissions seem to run on a quite complicated internal system that was written in the original ICBM. Essentially when you click buttons on the client it will construct a text command that it sends to the server, which is why it apparently requires creative.
It might be that it is as simple as setting a few permissions, but I will take a look at it when I have the time. Hopefully during the coming week =)

**Comment by godemperoroftheworld** [comment]
Thank you so much!

**Comment by godemperoroftheworld** [comment]
Any luck yet?

**Comment by wildex999** [comment]
Sorry, but it's just too much work fixing it. I have to learn the whole Sentry setup that the original developer did for turrets.
Sorry =(
